# Generated by Django 2.2.5 on 2019-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, unique=True, verbose_name='Company')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('account_number', models.CharField(max_length=200, unique=True, verbose_name='Account Number')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(editable=False, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
