# Generated by Django 2.2.5 on 2019-09-22 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_logo',
            field=models.ImageField(default=datetime.datetime(2019, 9, 22, 9, 18, 51, 201240, tzinfo=utc), upload_to='companies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='brand',
            field=models.CharField(max_length=200, unique=True, verbose_name='Brand'),
        ),
    ]
